import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, CircleHelp, FileText, Heart, LockKeyhole, Search, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { tools } from '../data/tools';
import { usePageMeta } from '../lib/utils';
import { TextInput } from '../components/ui';
import PrivacyCallout from '../components/PrivacyCallout';

export function AboutPage() {
  usePageMeta({ title: 'About QuicGen — Useful Tools, Thoughtfully Made', description: 'Meet QuicGen: a growing collection of thoughtful, free online tools built for speed, simplicity and privacy.', path: '/about', jsonLd: { '@context': 'https://schema.org', '@type': 'AboutPage', name: 'About QuicGen', url: `${window.location.origin}/about` } });
  return <main className="static-page page-wrap about-page"><div className="static-hero"><span className="eyebrow"><Sparkles size={14}/> THE IDEA BEHIND QUICGEN</span><h1>Make the little things<br/><span>feel effortless.</span></h1><p>We believe helpful tools should be just that: helpful. No hoops to jump through, no complicated interfaces, and no wondering where your data went.</p></div>
    <div className="about-feature-card"><div className="about-feature-icon"><span className="brand-mark"><span>q</span><i/></span></div><div><span className="eyebrow">GENERATE ANYTHING. INSTANTLY.</span><h2>A calmer corner of the internet.</h2><p>QuicGen brings the everyday tools you need into one welcoming home. Make a QR code. Find the right number. Clean up a piece of writing. Get on with your day.</p><p>We built QuicGen around the feeling we wanted from the web: quick when you need it, clear in how it works, and respectful of your time and your privacy.</p></div></div>
    <section className="about-values"><div className="about-value"><span><Zap size={19}/></span><h3>Quick by nature</h3><p>Results appear instantly because each tool does its work right in your browser.</p></div><div className="about-value"><span><ShieldCheck size={19}/></span><h3>Private by default</h3><p>Your tool inputs stay on your device. There’s no account and no content upload.</p></div><div className="about-value"><span><Heart size={19}/></span><h3>Made with care</h3><p>Little details matter: clear guidance, useful defaults and room to breathe.</p></div></section>
    <div className="about-cta"><div><span className="eyebrow">SOMETHING HANDY, JUST A CLICK AWAY</span><h2>Find your new favorite.</h2></div><Link to="/#tools" className="button button-primary">Explore the toolbox <ArrowRight size={15}/></Link></div>
    <p className="about-feedback">Have an idea for a tool or a way to make QuicGen better? <a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer">Share it on GitHub <ArrowUpRight size={13}/></a>.</p>
  </main>;
}

export function PrivacyPage() {
  usePageMeta({ title: 'Privacy Policy — Your Data Stays Yours', description: 'Read how QuicGen protects your privacy: your tool inputs stay in your browser, with transparent details about local storage and site hosting.', path: '/privacy', jsonLd: { '@context': 'https://schema.org', '@type': 'WebPage', name: 'QuicGen Privacy Policy', dateModified: '2026-10-08', url: `${window.location.origin}/privacy` } });
  return <main className="static-page page-wrap policy-page"><div className="static-page-heading"><div className="static-page-icon"><ShieldCheck size={22}/></div><span className="eyebrow">CLEAR, HUMAN, NO SMALL PRINT</span><h1>Privacy, plain and simple.</h1><p className="page-lede">Your work stays yours. Here’s exactly what that means.</p><p className="updated-label">Last updated: <time dateTime="2026-10-08">October 8, 2026</time></p></div>
    <div className="policy-layout"><aside className="policy-toc"><span className="eyebrow">ON THIS PAGE</span><a href="#overview">At a glance</a><a href="#tool-inputs">Your tool inputs</a><a href="#local-storage">Local storage</a><a href="#site-requests">Website requests</a><a href="#ads">Advertising</a><a href="#your-choices">Your choices</a><a href="#contact">Contact</a><div className="policy-toc-note"><LockKeyhole size={15}/><span>Content you enter into tools is never sent to QuicGen.</span></div></aside>
      <article className="policy-article"><section id="overview"><span className="policy-section-number">01</span><h2>At a glance</h2><p>QuicGen is designed to work entirely in your browser. You can generate a QR code, count words, calculate a tip, or convert text without creating an account or sending your inputs to us.</p><ul className="policy-check-list"><li><Check size={15}/>Tool inputs and results stay on your device.</li><li><Check size={15}/>No analytics, tracking pixels, or advertising cookies are used by this app.</li><li><Check size={15}/>The only information saved locally is your theme preference and, if you opt in, password history.</li></ul><PrivacyCallout/></section>
      <section id="tool-inputs"><span className="policy-section-number">02</span><h2>Information you enter into a tool</h2><p>Text, numbers, color values, images you choose, QR code contents, generated passwords, and other tool inputs are processed by JavaScript in your browser. QuicGen does not transmit this content to our servers. It is not logged by QuicGen or saved automatically.</p><p>Some results are intentionally stored only if you choose a feature that saves them locally—for example, turning on password history. A QR logo image is read locally to render your preview and is not uploaded.</p><p>Please still use care with highly sensitive information on any shared or compromised device. Anyone with access to your browser or screen could see information open in the page.</p></section>
      <section id="local-storage"><span className="policy-section-number">03</span><h2>Local storage and your choices</h2><p>QuicGen uses your browser’s local storage for a small number of settings:</p><ul><li><strong>Theme:</strong> your selected light or dark appearance.</li><li><strong>Password history:</strong> only when you switch on the opt-in history feature. It stores up to five generated passwords on this device so you can copy them again.</li></ul><p>We do not store your other tool inputs in local storage. You can turn off password history inside the password generator. To remove all QuicGen preferences and saved history, use <strong>Privacy first</strong> in the top navigation, then choose “Clear all QuicGen data.”</p><p>Clearing site data in your browser also removes these settings.</p></section>
      <section id="site-requests"><span className="policy-section-number">04</span><h2>Website delivery and technical requests</h2><p>QuicGen is a client-side website. Your browser does make ordinary requests to the website host to download the app and its files. Like most web hosts, the hosting or content-delivery provider may process basic connection details—such as an IP address, browser type, requested file and request time—to deliver and secure the site. These requests do not include the content you type into a QuicGen tool.</p><p>QuicGen itself does not run analytics, create tracking profiles, or access your tool inputs remotely. Browser extensions, your internet provider, and device management software operate independently of QuicGen.</p></section>
      <section id="ads"><span className="policy-section-number">05</span><h2>Advertising and third-party services</h2><p>QuicGen does not currently load advertising, analytics, or third-party tracking scripts. Pages may include clearly labeled space reserved for future, relevant advertising; a placeholder is not an ad and does not set cookies.</p><p>If advertising is introduced, this policy will be updated before it goes live to explain which provider is used, what information it may process, and the choices available to you. Third-party providers have their own privacy terms.</p></section>
      <section id="your-choices"><span className="policy-section-number">06</span><h2>Your choices</h2><p>You can use QuicGen without an account. You can opt out of local password history, switch themes, or remove QuicGen data at any time. You can also block local storage in your browser, though your theme preference and optional history will not persist.</p><p>Because we do not collect tool content, we do not have a server-side copy to retrieve, correct, or delete. The tool content remains in your browser and disappears when you close the page unless you choose to save it elsewhere.</p></section>
      <section id="contact"><span className="policy-section-number">07</span><h2>Questions or updates</h2><p>For a privacy question, bug report, or policy concern, please open an issue in the <a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer">QuicGen GitHub repository</a>. Please do not include passwords or other sensitive information in a public issue.</p><p>We may update this policy when the site changes. The date at the top shows when it was last revised.</p></section></article></div>
  </main>;
}

const helpFaqs = [
  { question: 'Do I need to install anything or create an account?', answer: 'No. Open a tool and use it right away. There are no accounts, sign-up forms, browser extensions or paid tiers.' },
  { question: 'Does QuicGen collect what I type?', answer: 'No. Tool inputs are processed in your browser and are not sent to QuicGen. This includes the text you count, QR content, color values and files you select for a preview.' },
  { question: 'Why is my password history off by default?', answer: 'Generated passwords can be sensitive, so history is opt-in. Turn on “Save history on this device” only if you want the last few generated passwords available in your browser’s local storage.' },
  { question: 'Can I use QuicGen on a phone or tablet?', answer: 'Yes. Pages and tool controls adapt to smaller screens. For the best experience, use a current browser and keep your device software up to date.' },
  { question: 'What happens if I clear my QuicGen data?', answer: 'The privacy controls remove QuicGen preferences and saved password history from your browser, then reload the page. Tool results and inputs are not stored by the site.' },
  { question: 'Is the hash generator suitable for passwords?', answer: 'No. MD5, SHA-1 and SHA-256 are fast general-purpose hashes, not password-storage algorithms. Use a dedicated password manager and a purpose-built password hashing scheme on the system that manages accounts.' },
  { question: 'How do I ask for a new tool or report a problem?', answer: 'Visit the QuicGen GitHub issues page. Please do not post private text, passwords or personal data in a public issue.' },
];

export function HelpPage() {
  const [search, setSearch] = useState('');
  usePageMeta({ title: 'Help Center — Guides, FAQs & Privacy', description: 'Learn how to use QuicGen tools, understand what happens to your data, and find answers to common questions.', path: '/help', jsonLd: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: helpFaqs.slice(0, 5).map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) } });
  const filteredTools = tools.filter((tool) => !search.trim() || `${tool.title} ${tool.description} ${tool.keywords.join(' ')}`.toLowerCase().includes(search.trim().toLowerCase()));
  return <main className="static-page page-wrap help-page"><div className="help-hero"><div className="static-page-icon"><CircleHelp size={22}/></div><span className="eyebrow">HERE IF YOU NEED US</span><h1>Let’s make it easy.</h1><p>Quick tips, straight answers and a little help finding your way.</p><label className="help-search"><Search size={18}/><TextInput value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find a tool or search a question…" aria-label="Search tools in the help center"/>{search && <button onClick={() => setSearch('')} aria-label="Clear search">×</button>}</label></div>
    <div className="help-content"><section className="help-tools-section"><div className="section-heading"><span className="eyebrow">TOOL GUIDES</span><h2>Pick up where you need help.</h2><p>Every tool includes a short, step-by-step guide on its page.</p></div><div className="help-tool-grid">{filteredTools.slice(0, 6).map((tool) => { const Icon = tool.icon; return <Link className="help-tool-link" key={tool.slug} to={`/${tool.slug}`}><span className={`help-tool-icon accent-${tool.accent}`}><Icon size={17}/></span><span><strong>{tool.title}</strong><small>{tool.description}</small></span><ArrowRight size={15}/></Link>; })}{filteredTools.length === 0 && <div className="help-no-results">No tools matched that search. Try another word.</div>}</div><Link to="/#tools" className="text-link help-all-tools">Browse all {tools.length} tools <ArrowRight size={14}/></Link></section>
      <section className="help-privacy-section" id="privacy"><div className="section-heading"><span className="eyebrow">YOUR PRIVACY, EXPLAINED</span><h2>It stays on your device.</h2><p>QuicGen runs its tools in your browser. Your text, files and results aren’t sent to us.</p></div><PrivacyCallout/><Link to="/privacy" className="text-link">Read the full privacy policy <ArrowRight size={14}/></Link></section>
      <section className="faq-section"><div className="section-heading"><span className="eyebrow">FREQUENTLY ASKED</span><h2>Good questions, good answers.</h2></div><div className="help-faq-list">{helpFaqs.map((faq, index) => <details className="help-faq" key={faq.question} open={index === 0}><summary>{faq.question}<ChevronDown size={18}/></summary><p>{faq.answer}</p></details>)}</div></section>
      <div className="help-support-card"><span><FileText size={18}/></span><div><strong>Still need a hand?</strong><p>Tell us what’s up. We’ll do our best to point you in the right direction.</p></div><a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer" className="button button-secondary">Ask on GitHub <ArrowUpRight size={14}/></a></div>
    </div></main>;
}

export function NotFoundPage() {
  usePageMeta({ title: 'Page Not Found', description: 'We could not find that page. Return to QuicGen to explore our free, private online tools.', path: '/404', robots: 'noindex, follow' });
  const [query, setQuery] = useState('');
  const found = tools.filter((tool) => !query || `${tool.title} ${tool.description}`.toLowerCase().includes(query.toLowerCase())).slice(0, 4);
  return <main className="not-found-page page-wrap"><div className="not-found-card"><span className="not-found-number">404</span><span className="eyebrow">WELL, THIS IS AWKWARD</span><h1>We can’t find that page.</h1><p>Maybe it moved. Maybe the link took a wrong turn. Let’s get you back to something useful.</p><label className="not-found-search"><Search size={17}/><TextInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tools instead…" aria-label="Search available tools"/></label><div className="not-found-links">{found.map((tool) => <Link to={`/${tool.slug}`} key={tool.slug}>{tool.title}<ArrowUpRight size={14}/></Link>)}</div><Link to="/" className="button button-primary"><ArrowRight size={15} className="not-found-home-arrow"/>Go to the homepage</Link></div><div className="not-found-decoration" aria-hidden="true"><span>✳</span><span>✦</span></div></main>;
}
