import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleHelp, FileText, Heart, LockKeyhole, Search, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { tools } from '../data/tools';
import { siteUrl, usePageMeta } from '../lib/utils';
import { TextInput } from '../components/ui';
import PrivacyCallout from '../components/PrivacyCallout';
import { searchTools } from '../lib/search';
import { guides, guidePath } from '../data/guides';
import { topics, topicPath } from '../data/topics';

export function AboutPage() {
  usePageMeta({
    title: 'About QuicGen — Private, Useful Tools for Everyday Work',
    description: 'Learn why QuicGen exists, how its browser-based tools protect your inputs, who they are designed for and the principles behind the product.',
    path: '/about',
    jsonLd: [
      { '@context': 'https://schema.org', '@type': 'AboutPage', name: 'About QuicGen', url: `${siteUrl}/about`, description: 'The mission, privacy philosophy and product principles behind QuicGen.' },
      { '@context': 'https://schema.org', '@type': 'Organization', name: 'QuicGen', url: siteUrl, sameAs: ['https://github.com/nnamdimichael020-wq/quicgen'] },
    ],
  });
  return <main className="static-page page-wrap about-page">
    <header className="about-hero-long"><span className="eyebrow"><Sparkles size={14}/> THE IDEA BEHIND QUICGEN</span><h1>Useful tools.<br/><span>Less friction. More trust.</span></h1><p>QuicGen brings everyday online tools into one calm, dependable place—fast enough to feel instant, clear enough to use confidently and designed to keep the work you enter on your device.</p><div className="about-hero-actions"><Link to="/#tools" className="button button-primary">Explore all {tools.length} tools <ArrowRight size={15}/></Link><Link to="/privacy" className="text-link">Read our privacy policy <ArrowUpRight size={14}/></Link></div></header>
    <article className="about-story">
      <section className="about-story-intro"><span className="about-story-icon"><span className="brand-mark"><span>q</span><i/></span></span><div><span className="eyebrow">OUR MISSION</span><h2>A calmer corner of the internet.</h2><p>Most useful tasks should not require a new account, a complicated dashboard or a long wait. Sometimes you need to make a QR code, count a draft, convert a color or check a number, then get on with the rest of your day. QuicGen is built for those everyday moments.</p><p>We believe a small tool can still feel thoughtful. Its purpose should be obvious, its result easy to verify and its privacy behavior understandable before you type. That belief shapes the product from the first screen to the final download.</p></div></section>
      <section className="about-editorial-section"><span className="eyebrow">HOW THE TOOLS WORK</span><h2>Processing happens in your browser.</h2><p>QuicGen’s tools use JavaScript running on your device to generate, calculate, format or transform the information you enter. The QR payload, text draft, dates, colors, hashes and generated values are processed in the current browser page; they are not sent to a QuicGen application server. No account is required, and the product does not need a database of your tool inputs to work.</p><p>This architecture is practical as well as privacy-minded: many results appear immediately, the tools remain usable without a separate processing service, and your content stays with the device you are already using. Downloads and clipboard actions happen through browser capabilities that you choose to invoke.</p><p>There is an important distinction between tool processing and delivering the website. Your browser still requests the app and its assets from the hosting provider. As described in our <Link to="/privacy">privacy policy</Link>, a host may process ordinary technical connection details needed to serve and secure those requests. Browser extensions, shared screens, clipboard managers and device monitoring also operate outside QuicGen’s control.</p></section>
      <section className="about-editorial-section about-principles"><span className="eyebrow">THE PRINCIPLES WE BUILD BY</span><h2>Clear, private and useful by default.</h2><div className="about-values about-values-long"><div className="about-value"><span><Zap size={19}/></span><h3>Speed with purpose</h3><p>Useful defaults, immediate feedback and a short path from question to result. Performance should remove waiting, not hide what a tool is doing.</p></div><div className="about-value"><span><ShieldCheck size={19}/></span><h3>Privacy as a product choice</h3><p>Client-side processing, no accounts and explicit local-storage choices reduce data collection instead of asking people to trust an invisible promise.</p></div><div className="about-value"><span><Heart size={19}/></span><h3>Care in the details</h3><p>Readable interfaces, keyboard access, mobile layouts, helpful validation and clear error states make a small utility more dependable.</p></div><div className="about-value"><span><Check size={19}/></span><h3>Honest about limits</h3><p>A calculation is not financial advice, a hash is not encryption and a password score is not a security guarantee. The interface should say so.</p></div></div></section>
      <section className="about-editorial-section"><span className="eyebrow">WHO QUICGEN IS FOR</span><h2>Small tasks, many kinds of work.</h2><p>Students can check writing length, calculate a percentage or create placeholder copy. Designers can explore colors and prepare QR artwork. Developers can generate UUIDs, inspect Base64 text or compare a SHA-256 digest. A host can make a Wi-Fi code, a team can split a dinner bill and anyone can roll a virtual die when the physical set is in another room.</p><p>These examples share a simple requirement: the tool should be quick to understand and useful without collecting more information than the task needs. We build for curious people, busy people and people who simply want a straightforward answer without signing up for another service.</p><div className="about-inline-links"><Link to="/topics/qr-codes">Explore QR code guides <ArrowRight size={13}/></Link><Link to="/topics/calculators">Browse calculators <ArrowRight size={13}/></Link><Link to="/topics/password-security">Read password-security guides <ArrowRight size={13}/></Link></div></section>
      <section className="about-editorial-section about-data-section"><span className="eyebrow">WHAT IS STORED</span><h2>Specific choices, not hidden histories.</h2><p>Tool inputs are not saved automatically. The site stores your chosen theme and your response to the optional bookmark reminder so those choices are remembered on this device. Password history is off by default and saved only when you explicitly turn that option on. Those preferences stay in the current browser profile; they do not sync through a QuicGen account.</p><p>You can turn off password history in the password tool or clear QuicGen preferences from the privacy controls in the header. Blocking browser storage may prevent preferences from persisting, but it does not prevent the tools from calculating in the current page. We keep this model deliberately small and explain each storage choice in plain language.</p></section>
      <section className="about-editorial-section"><span className="eyebrow">TRUST, WITHOUT THE HYPE</span><h2>Useful signals you can check.</h2><ul className="about-trust-list"><li><ShieldCheck size={16}/><span><strong>No account or upload workflow</strong><small>Open a tool and work in the page; inputs are not submitted to a QuicGen processing API.</small></span></li><li><LockKeyhole size={16}/><span><strong>Visible privacy details</strong><small>Each tool includes a privacy badge, and the <Link to="/privacy">full policy</Link> explains storage and ordinary hosting requests.</small></span></li><li><FileText size={16}/><span><strong>Guides paired with real tools</strong><small>Our <Link to="/blog">practical guides</Link> link to the actual tool pages, explain limitations and include worked examples.</small></span></li><li><ArrowUpRight size={16}/><span><strong>Public source and feedback channel</strong><small>Review the <a href="https://github.com/nnamdimichael020-wq/quicgen" target="_blank" rel="noreferrer">QuicGen GitHub repository</a> or report a problem without posting private data.</small></span></li></ul><p>Trust is not a badge we can award ourselves. It comes from setting clear expectations, shipping what we describe and correcting the product when it falls short. We welcome reports that help us do that.</p></section>
      <section className="about-editorial-section"><span className="eyebrow">A NOTE ON RESPONSIBLE USE</span><h2>Fast tools still deserve careful judgment.</h2><p>QuicGen is designed for everyday productivity, not as a replacement for specialist systems. Do not use an informal random draw where audited selection is required, treat an online checksum as proof of authenticity without a trusted source, or rely on a general calculator for a legal, medical, payroll or financial determination. Review results before you share or act on them.</p><p>Our goal is not to make every decision for you. It is to make the small, mechanical part of a task easier while keeping the assumptions and limits visible.</p></section>
    </article>
    <section className="about-bottom-cta"><div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Find the tool that gets you moving.</h2><p>Browse the toolbox or read a practical guide first.</p></div><div><Link to="/#tools" className="button button-primary">Explore tools <ArrowRight size={15}/></Link><Link to="/blog" className="button button-secondary">Read the guides <BookOpen size={14}/></Link></div></section>
    <p className="about-feedback">Have an idea, a question or a bug report? <a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer">Share it on GitHub <ArrowUpRight size={13}/></a>. Please do not include passwords or private content.</p>
  </main>;
}

export function PrivacyPage() {
  usePageMeta({ title: 'Privacy Policy — Your Data Stays Yours', description: 'Read how QuicGen protects your privacy: your tool inputs stay in your browser, with transparent details about local storage and site hosting.', path: '/privacy', jsonLd: { '@context': 'https://schema.org', '@type': 'WebPage', name: 'QuicGen Privacy Policy', dateModified: '2026-10-09', url: `${siteUrl}/privacy` } });
  return <main className="static-page page-wrap policy-page"><div className="static-page-heading"><div className="static-page-icon"><ShieldCheck size={22}/></div><span className="eyebrow">CLEAR, HUMAN, NO SMALL PRINT</span><h1>Privacy, plain and simple.</h1><p className="page-lede">Your work stays yours. Here’s exactly what that means.</p><p className="updated-label">Last updated: <time dateTime="2026-10-09">October 9, 2026</time></p></div>
    <div className="policy-layout"><aside className="policy-toc"><span className="eyebrow">ON THIS PAGE</span><a href="#overview">At a glance</a><a href="#tool-inputs">Your tool inputs</a><a href="#local-storage">Local storage</a><a href="#site-requests">Website requests</a><a href="#ads">Advertising</a><a href="#your-choices">Your choices</a><a href="#contact">Contact</a><div className="policy-toc-note"><LockKeyhole size={15}/><span>Content you enter into tools is never sent to QuicGen.</span></div></aside>
      <article className="policy-article"><section id="overview"><span className="policy-section-number">01</span><h2>At a glance</h2><p>QuicGen is designed to work entirely in your browser. You can generate a QR code, count words, calculate a tip, or convert text without creating an account or sending your inputs to us.</p><ul className="policy-check-list"><li><Check size={15}/>Tool inputs and results stay on your device.</li><li><Check size={15}/>No analytics, tracking pixels, or advertising cookies are used by this app.</li><li><Check size={15}/>Small preferences such as your theme and bookmark-reminder choice, plus password history only if you opt in, are saved locally.</li></ul><PrivacyCallout/></section>
      <section id="tool-inputs"><span className="policy-section-number">02</span><h2>Information you enter into a tool</h2><p>Text, numbers, color values, images you choose, QR code contents, generated passwords, and other tool inputs are processed by JavaScript in your browser. QuicGen does not transmit this content to our servers. It is not logged by QuicGen or saved automatically.</p><p>Some results are intentionally stored only if you choose a feature that saves them locally—for example, turning on password history. A QR logo image is read locally to render your preview and is not uploaded.</p><p>Please still use care with highly sensitive information on any shared or compromised device. Anyone with access to your browser or screen could see information open in the page.</p></section>
      <section id="local-storage"><span className="policy-section-number">03</span><h2>Local storage and your choices</h2><p>QuicGen uses your browser’s local storage for a small number of settings:</p><ul><li><strong>Theme:</strong> your selected light or dark appearance.</li><li><strong>Bookmark reminder:</strong> whether you accepted or dismissed the one-time save-this-site prompt.</li><li><strong>Password history:</strong> only when you switch on the opt-in history feature. It stores up to five generated passwords on this device so you can copy them again.</li></ul><p>We do not store your other tool inputs in local storage. You can turn off password history inside the password generator. To remove all QuicGen preferences and saved history, use <strong>Privacy first</strong> in the top navigation, then choose “Clear all QuicGen data.”</p><p>Clearing site data in your browser also removes these settings.</p></section>
      <section id="site-requests"><span className="policy-section-number">04</span><h2>Website delivery and technical requests</h2><p>QuicGen is a client-side website. Your browser does make ordinary requests to the website host to download the app and its files. Like most web hosts, the hosting or content-delivery provider may process basic connection details—such as an IP address, browser type, requested file and request time—to deliver and secure the site. These requests do not include the content you type into a QuicGen tool.</p><p>QuicGen itself does not run analytics, create tracking profiles, or access your tool inputs remotely. Browser extensions, your internet provider, and device management software operate independently of QuicGen.</p></section>
      <section id="ads"><span className="policy-section-number">05</span><h2>Advertising and third-party services</h2><p>QuicGen does not currently load advertising, analytics, or third-party tracking scripts. QuicGen pages do not currently contain advertising placements or third-party promotional embeds.</p><p>If advertising is introduced, this policy will be updated before it goes live to explain which provider is used, what information it may process, and the choices available to you. Third-party providers have their own privacy terms.</p></section>
      <section id="your-choices"><span className="policy-section-number">06</span><h2>Your choices</h2><p>You can use QuicGen without an account. You can accept or dismiss the optional bookmark reminder, opt out of local password history, switch themes, or remove QuicGen data at any time. You can also block local storage in your browser, though these preferences and optional history may not persist.</p><p>Because we do not collect tool content, we do not have a server-side copy to retrieve, correct, or delete. The tool content remains in your browser and disappears when you close the page unless you choose to save it elsewhere.</p></section>
      <section id="contact"><span className="policy-section-number">07</span><h2>Questions or updates</h2><p>For a privacy question, bug report, or policy concern, please open an issue in the <a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer">QuicGen GitHub repository</a>. Please do not include passwords or other sensitive information in a public issue.</p><p>We may update this policy when the site changes. The date at the top shows when it was last revised.</p></section></article></div>
  </main>;
}

const helpFaqs = [
  { question: 'Do I need to install anything or create an account?', answer: 'No. Open a tool and use it right away. There are no accounts, sign-up forms, browser extensions or paid tiers.' },
  { question: 'Does QuicGen collect what I type?', answer: 'No. Tool inputs are processed in your browser and are not sent to QuicGen. This includes the text you count, QR content, color values and files you select for a preview.' },
  { question: 'Why is my password history off by default?', answer: 'Generated passwords can be sensitive, so history is opt-in. Turn on “Save history on this device” only if you want the last few generated passwords available in your browser’s local storage.' },
  { question: 'Can I use QuicGen on a phone or tablet?', answer: 'Yes. Pages and tool controls adapt to smaller screens. For the best experience, use a current browser and keep your device software up to date.' },
  { question: 'What happens if I clear my QuicGen data?', answer: 'The privacy controls remove QuicGen preferences and saved password history from your browser, then reload the page. Tool results and inputs are not stored by the site.' },
  { question: 'How does the bookmark reminder work?', answer: 'After a successful tool action, QuicGen may show one optional reminder to save the site. Your accept or dismiss choice is remembered on this device, and you can clear that preference from Privacy first. Browser installation is offered only when your browser supports it.' },
  { question: 'Is the hash generator suitable for passwords?', answer: 'No. MD5, SHA-1 and SHA-256 are fast general-purpose hashes, not password-storage algorithms. Use a dedicated password manager and a purpose-built password hashing scheme on the system that manages accounts.' },
  { question: 'How do I ask for a new tool or report a problem?', answer: 'Visit the QuicGen GitHub issues page. Please do not post private text, passwords or personal data in a public issue.' },
];

export function HelpPage() {
  const [search, setSearch] = useState('');
  usePageMeta({ title: 'Help Center — Guides, FAQs & Privacy', description: 'Learn how to use QuicGen tools, understand what happens to your data, and find answers to common questions.', path: '/help', jsonLd: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: helpFaqs.slice(0, 5).map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) } });
  const normalizedSearch = search.trim().toLocaleLowerCase();
  const filteredTools = normalizedSearch ? searchTools(search) : tools;
  const visibleGuides = guides.filter((guide) => !normalizedSearch || `${guide.title} ${guide.description} ${guide.excerpt} ${guide.topics.join(' ')}`.toLocaleLowerCase().includes(normalizedSearch)).slice(0, normalizedSearch ? 5 : 3);
  const visibleTopics = topics.filter((topic) => !normalizedSearch || `${topic.title} ${topic.description} ${topic.eyebrow} ${topic.intro.join(' ')}`.toLocaleLowerCase().includes(normalizedSearch)).slice(0, normalizedSearch ? 4 : 4);
  const filteredFaqs = helpFaqs.filter((faq) => !normalizedSearch || `${faq.question} ${faq.answer}`.toLocaleLowerCase().includes(normalizedSearch));
  return <main className="static-page page-wrap help-page"><div className="help-hero"><div className="static-page-icon"><CircleHelp size={22}/></div><span className="eyebrow">HERE IF YOU NEED US</span><h1>Let’s make it easy.</h1><p>Quick tips, straight answers and a little help finding your way.</p><label className="help-search"><Search size={18}/><TextInput value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tools, guides or help topics…" aria-label="Search tools and help topics"/>{search && <button type="button" onClick={() => setSearch('')} aria-label="Clear search">×</button>}</label></div>
    <div className="help-content"><section className="help-tools-section"><div className="section-heading"><span className="eyebrow">TOOL GUIDES</span><h2>{search ? 'Matching tools' : 'Pick up where you need help.'}</h2><p>Every tool includes a step-by-step guide on its page.</p></div><div className="help-tool-grid">{filteredTools.slice(0, search ? tools.length : 6).map((tool) => { const Icon = tool.icon; return <Link className="help-tool-link" key={tool.slug} to={`/${tool.slug}`}><span className={`help-tool-icon accent-${tool.accent}`}><Icon size={17}/></span><span><strong>{tool.title}</strong><small>{tool.description}</small></span><ArrowRight size={15}/></Link>; })}{filteredTools.length === 0 && <div className="help-no-results">No tools matched. Try a different task or spelling.</div>}</div><Link to="/#tools" className="text-link help-all-tools">Browse all {tools.length} tools <ArrowRight size={14}/></Link></section>
      {(visibleGuides.length > 0 || visibleTopics.length > 0) && <section className="help-resources-section"><div className="section-heading"><span className="eyebrow">GUIDES &amp; TOPICS</span><h2>{normalizedSearch ? 'More useful matches.' : 'Learn a little more.'}</h2><p>Step-by-step help and focused collections for common tasks.</p></div><div className="help-resource-grid">{visibleGuides.map((guide) => <Link className="help-resource-link" key={guide.slug} to={guidePath(guide.slug)}><span className="help-resource-icon"><BookOpen size={16}/></span><span><small>PRACTICAL GUIDE</small><strong>{guide.title}</strong><em>{guide.excerpt}</em></span><ArrowRight size={14}/></Link>)}{visibleTopics.map((topic) => <Link className="help-resource-link help-topic-resource" key={topic.slug} to={topicPath(topic.slug)}><span className="help-resource-icon"><BookOpen size={16}/></span><span><small>TOPIC COLLECTION</small><strong>{topic.title}</strong><em>{topic.description}</em></span><ArrowRight size={14}/></Link>)}</div>{!normalizedSearch && <Link to="/blog" className="text-link help-all-tools">Browse all {guides.length} guides <ArrowRight size={14}/></Link>}</section>}
      <section className="help-privacy-section" id="privacy"><div className="section-heading"><span className="eyebrow">YOUR PRIVACY, EXPLAINED</span><h2>It stays on your device.</h2><p>QuicGen runs its tools in your browser. Your text, files and results aren’t sent to us.</p></div><PrivacyCallout/><Link to="/privacy" className="text-link">Read the full privacy policy <ArrowRight size={14}/></Link></section>
      <section className="faq-section"><div className="section-heading"><span className="eyebrow">FREQUENTLY ASKED</span><h2>{search ? 'Matching help topics' : 'Good questions, good answers.'}</h2></div><div className="help-faq-list">{filteredFaqs.map((faq, index) => <details className="help-faq" key={faq.question} open={index === 0}><summary>{faq.question}<ChevronDown size={18}/></summary><p>{faq.answer}</p></details>)}{search && filteredFaqs.length === 0 && <p className="help-no-results">No help topics matched. Try a different phrase.</p>}</div></section>
      <div className="help-support-card"><span><FileText size={18}/></span><div><strong>Still need a hand?</strong><p>Tell us what’s up. We’ll do our best to point you in the right direction.</p></div><a href="https://github.com/nnamdimichael020-wq/quicgen/issues" target="_blank" rel="noreferrer" className="button button-secondary">Ask on GitHub <ArrowUpRight size={14}/></a></div>
    </div></main>;
}

export function NotFoundPage() {
  usePageMeta({ title: 'Page Not Found', description: 'We could not find that page. Return to QuicGen to explore our free, private online tools.', path: '/not-found', robots: 'noindex, follow' });
  const [query, setQuery] = useState('');
  const found = query.trim() ? searchTools(query, 4) : tools.slice(0, 4);
  return <main className="not-found-page page-wrap"><div className="not-found-card"><span className="not-found-number">404</span><span className="eyebrow">WELL, THIS IS AWKWARD</span><h1>We can’t find that page.</h1><p>Maybe it moved. Maybe the link took a wrong turn. Let’s get you back to something useful.</p><label className="not-found-search"><Search size={17}/><TextInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tools instead…" aria-label="Search available tools"/></label><div className="not-found-links">{found.map((tool) => <Link to={`/${tool.slug}`} key={tool.slug}>{tool.title}<ArrowUpRight size={14}/></Link>)}{found.length === 0 && <p className="not-found-no-results">No matching tools. Try another search or browse the full toolbox.</p>}</div><Link to="/" className="button button-primary"><ArrowRight size={15} className="not-found-home-arrow"/>Go to the homepage</Link></div><div className="not-found-decoration" aria-hidden="true"><span>✳</span><span>✦</span></div></main>;
}
